sudo: false
install: true

addons:
  sonarcloud:
    organization: "rajeshpv-poc"
    token:
      secure: "d198f3f0785ead9dd1cc8665785bcb4311501710" # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar